stages:
  - analyze
  - test
  - build
  
variables:
  BUILD_DIR: build
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  
build:
  stage: build
  tags:
    - macos
  before_script:
    - swift --version
    - echo 'import Foundation; print("Foundation available!")' > test.swift
    - swift test.swift
    - swift --version
  script:
    - swift build --build-path $BUILD_DIR
  artifacts:
    paths:
      - $BUILD_DIR
      
test:
  stage: test
  tags:
    - macos
  before_script:
    - swift --version
    - echo 'import Foundation; print("Foundation available!")' > test.swift
    - swift test.swift
    - swift --version
  script:
    - swift test --build-path $BUILD_DIR

analyze:
  stage: analyze
  tags: 
    - kubernetes
  image:
    name: sonarsource/sonar-scanner-cli:11
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/
  script: 
    - sonar-scanner -Dsonar.host.url="${SONAR_HOST_URL}"
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'
