stages:
  - build
  - test
  
variables:
  BUILD_DIR: build
  
before_script:
  - swift --version
  - echo 'import Foundation; print("Foundation available!")' > test.swift
  - swift test.swift
  - swift --version
  
build:
  stage: build
  tags:
    - macos
  script:
    - swift build --build-path $BUILD_DIR
  artifacts:
    paths:
      - $BUILD_DIR
      
test:
  stage: test
  tags:
    - macos
  script:
    - swift test --build-path $BUILD_DIR
